name: run test
on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout repo
      uses: actions/checkout@main
      with:
        submodules: 'true'
    - name: setup python-version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: install brew packages
      run: brew install w3m
    - name: apt install
      run: apt-get update && apt-get install w3m -y
    - name: setup venv
      run: make venv
    - name: run make
      run: make venv-force && . venv/bin/activate && make
