name: run test
on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout repo
      uses: actions/checkout@main
      with:
        submodules: 'true'
    - name: Set up Homebrew
      if: ${{ startsWith(matrix.os, 'macos') }}
      uses: Homebrew/actions/setup-homebrew@master
    - name: make install-dependencies
      run: make install-dependencies
    - name: setup python-version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: setup venv
      run: make venv-force
    - name: run make
      run: . venv/bin/activate && make
